// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nhpatxjhupxsfdvoijjo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ocGF0eGpodXB4c2Zkdm9pampvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0ODQ0MTAsImV4cCI6MjA3MzA2MDQxMH0.slu3LHmiJ8No_x4gntB1CkGCxJwlpp6f0fcWVJrrmak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});